//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ManufName { get; set; }
        public string ExpDate { get; set; }
        public int DownLimit { get; set; }
        public int Quantity { get; set; }
        public int PurchasePrice { get; set; }
        public int SalePrice { get; set; }
        public string ImagePath { get; set; }
        public string PurchaseDate { get; set; }
    }
}
